package:
  name: fingerseq
  version: 0.1.0

source:
  url: https://bitbucket.org/genomicepidemiology/fingerseq/get/0.1.0.tar.gz

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - fingerseq -h | grep fingerseq >/dev/null

about:
  home: https://bitbucket.org/genomicepidemiology/fingerseq
  summary: 'fingerseq extracts basic information about sequence samples, such as the predicted technology, phred scale and whether the sample is paired end.'
  license: Apache-2.0